new: vanilla JS example
maticnetwork/wallet-widget-example pull request #4
Opened 2021-12-20 12:07 UTC by wolf76

2021-12-21 08:27 UTC, ujjwalgupta94 requested changes

2021-12-21 08:27 UTC, ujjwalgupta94 commented on vanilla/app.js
> +async function myFunction() {
could you make the function name `openWidget` ,

2021-12-21 19:33 UTC, wolf76 commented on vanilla/app.js
> +async function myFunction() {
Changed the function name.

2021-12-22 06:19 UTC, ujjwalgupta94 approved these changes

2021-12-22 06:19 UTC, merged